### ISSUE TITLE
Wrong streamer and button not working

### ISSUE THREAD

**Issue by ImCoderax** [vippsas/vipps-streamlabs#11]
Set up everything like told in readme, no errors whatsoever. Push the gits to Heroku, and when accessing frontend, it's saying "Doner til Emzia". Never put in Emzia anywhere, and the "Doner med Vipps" button is not working either.

**Comment by Hakonslie** [comment]
Hi @ImCoderax sorry about the really late answer. I have changed the documentation and added the task to change the streamer name so it doesn't say "Doner til Emzia" for everyone. Also, regarding the button not working. Have you obtained a Vipps Merchant Account and changed the keys in the application.yaml file?  If so can you check Developer Tools and see what happens in the console when you click Doner med Vipps? Should display an error message

**Comment by ImCoderax** [comment]
Hi again, @Hakonslie! No worries about late replies. 😄 I can't see any changes made to the documentation (yet?), but I will keep my eyes open for changes. I've checked console when clikcing the button, and it's responding with POST Error code 500 (Internal Server Error). Trying to look into why this is happening, but no luck. I've also talked to Emzia, who currently also faces the same problem, with the button not working. She said she would look into it, but I haven't heard anything back about a fix. 😄 Any help is greatly appreciated! 😄

**Comment by Hakonslie** [comment]
@ImCoderax Do you have a vipps merchant account that you have obtained the keys for and inserted into the application.yaml file?

**Comment by renreine** [comment]
Hi, were you able to resolve the issue regarding 500 error code? I am experiencing the same issue.
I have obtained the keys and inserted them to application.yaml, but I am afraid I am entering something wrong. 

What is the difference between VIPPS_OCP_APIM_SUBSCRIPTION_KEY_ACCESSTOKEN and VIPPS_OCP_APIM_SUBSCRIPTION_KEY_ECOMMERCE? What keys should be entered in each of them? 

Thanks!

**Comment by Hakonslie** [comment]
Hi @renreine, sorry we have stopped developing this solution and it stands today only as an example of what can be done with Vipps API-s. If you need help in regards to keys or other things relevant to integration I suggest you have a look at https://github.com/vippsas/vipps-ecom-api 

Regards,
Håkon
