### ISSUE TITLE
Streamelements

### ISSUE THREAD

**Issue by senxaitv** [vippsas/vipps-streamlabs#17]
Heisann!

Er det mulig å bruker dette også via Streamelements?
Bruker streamelements overlay på OBS Studio pga mye lavere process forbruk enn SLOBs.
Har bruk SLOBs i lange peroide, men gikk over til SE pga akkurat det process forbruket, nå lagger ikke streamen lenger og minimalt forbruk av process :)

**Comment by Hakonslie** [comment]
Hei!
Det er ikke laget integrasjon mot streamelements, og vi jobber ikke med å vedlikeholde denne løsningen om dagen. Det er hovedsakelig ment for inspirasjon og eventuelt som et eksempel på integrasjon mot Vipps sine API-er :) 

Mvh
Håkon
